### ISSUE TITLE
Bug: Missing configuration

### ISSUE THREAD

**Issue by N1cky94** [N1cky94/userman#3]
# Bug: Missing Configuration

## Context

There is missing configuration that should be added or removed

## Acceptance Criteria

- [x] Change the `application.properties` file to a `.yml` file
- [x] Remove the weird `data.sql` file in the `main > resources` folder
- [x] Change the `Application.class` file to the correct one
- [x] Remove all unwanted code that is in the src package

## More info

The application.yml file should look like this to get started:
```yml
server:
  port: ${PORT:8080}
logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false

vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,be.archilios.usermanagement
  launch-browser: true
```

The Application.class class
```java
package be.archilios.usermanagement;

import com.vaadin.flow.component.dependency.NpmPackage;
import com.vaadin.flow.component.page.AppShellConfigurator;
import com.vaadin.flow.theme.Theme;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * The entry point of the Spring Boot application.
 *
 * Use the @PWA annotation make the application installable on phones, tablets
 * and some desktop browsers.
 *
 */
@SpringBootApplication
@NpmPackage(value = "@fontsource/arvo", version = "4.5.0")
@Theme(value = "userman")
public class Application implements AppShellConfigurator {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
```
